events {}

http {
    upstream leaderboard_cluster {
        ip_hash;
        server leaderboard:8084;
        server leaderboard2:8084;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://leaderboard_cluster;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;

            proxy_read_timeout 3600;
            proxy_send_timeout 3600;
        }
    }
}